apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-codegen-helm-181202-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/test-codegen-helm-181202/overlays/development
    repoURL: https://github.com/fpetk/test-codegen-helm-181202-gitops.git
    targetRevision: main
    helm:
      releaseName: test-codegen-helm-181202
  destination:
    namespace: rhdh-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: ai-rhdh
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
